In [9]:
import tensorflow as tf

In [10]:
tf.SparseTensor(indices=[[0,3],[2,4]], values=[10,20], dense_shape=[3,10])

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [11]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20], dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [12]:
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))


In [13]:
# Tensorflow Graphs

x = tf.compat.v1.get_variable('x', dtype=tf.int32, initializer=tf.constant([5]))
y = tf.compat.v1.get_variable('x', dtype=tf.int32, initializer=tf.constant([6]))

In [14]:
c = tf.constant([5], name='constant')
square = tf.constant([2], name = 'square')
f = tf.multiply(x,y) + tf.pow(x,square) + y + c
f

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([66], dtype=int32)>