In [1]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
tf.__version__

'2.17.0'

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [5]:
x=tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
y=tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [7]:
z=tf.constant('India')
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [8]:
s=tf.constant([1,2,3,4,5,6])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [9]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [10]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [12]:
t_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype='int32')
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
t_3d_1=tf.constant([[[1,2],[2,3],[3,4]]],dtype='float32')
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [14]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [15]:
t_3d_1.shape

TensorShape([1, 3, 2])

#Tensorflow Math Modules

In [16]:
import tensorflow as tf
import numpy as np

In [17]:
a=10
b=20
a+b

30

In [18]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [19]:
# Addition of two list

l1=[1,2,3,4]
l2=[5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [20]:
#Addition of two tuple

t1=(2,3,4,5)
t2=(5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [21]:
l1=[1,2,3,4]
a=10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [22]:
# Given a tensor x and a tensor y, this operation x*y computers for corresponding element in x and y

x=tf.constant([[2,2],[3,3]])
y=tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [23]:
# tf.math.abs
# Real Number

x=tf.constant([-2.25,3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [24]:
#tf.math.subtract

x=[1,2,3,4,5]
y=1
tf.subtract(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [25]:
x=[1,2,3,4,5]
y=1
tf.subtract(y,x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [26]:
#tf.math.multiply

import tensorflow as tf
x=tf.constant(([1,2,3,4]))
tf.math.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [27]:
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [28]:
tf.math.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [29]:
x=tf.ones([1,2])
y=tf.ones([2,1])
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [30]:
#tf.math.maximum

x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-2.,0.,2.,5.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [31]:
x=tf.constant([-5.,0.,0.,0.,])
y=tf.constant([-3.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [32]:
#tf.math.minimum

x=tf.constant([0.,0.,0.,0.])
y=tf.constant([-5.,-2.,0.,3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [33]:
x=tf.constant([-5.,0.,0.,0.])
y=tf.constant([-3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [34]:
# tf.math.log

x=tf.constant([0,0.5,1,1.5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  0.4054651], dtype=float32)>

In [35]:
# tf.math.divide

x=tf.constant([16,12,11])
y=tf.constant([4,6,2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [36]:
#tf.math.pow

x=tf.constant([[2,2],[3,3]])
y=tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [37]:
#tf.math.sqrt

x=tf.constant([[4.0],[16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [38]:
y=tf.constant([[-4.0],[16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [39]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [40]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [41]:
ones_2d=tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [42]:
ones_3d=tf.ones((2,2,4),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [43]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [44]:
zeros_2d=tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

#Tensorflow Variables

In [45]:
# Variable constructor requires an initial value for the variable which can be a tensor of any type & shape .
# This initial value defines the type & shape of the variable.
# After the construction the type & shape of the variable are fixed.

In [46]:
import tensorflow as tf

In [47]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [48]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [49]:
x.name

'Variable:0'

In [50]:
x.shape

TensorShape([4])

In [51]:
x.dtype

tf.int32

In [52]:
y=tf.Variable([1.0,2,3.3,4])
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [53]:
z=tf.Variable(True, False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [54]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [55]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

#Create Tensorflow variable with different shape

In [56]:
t_2d=tf.Variable([2,3],[4,5])
t_2d

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [57]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [58]:
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [59]:
# Get index of highest value

In [60]:
t_2d

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [61]:
tf.argmax(t_2d)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [62]:
# Viewed/Convert as a Tensor

In [63]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [64]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [65]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [66]:
# Change/Assign New Value to Tensor

In [67]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [68]:
x.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [69]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [70]:
x.assign([4,6,2,9])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [71]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [72]:
# Assign Variable with another Memory

In [73]:
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

In [74]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

#**Placeholder**-Migrate tensorflow 1 code to tensorflow 2

###Place holder is a variable that we will assign data to at a later date

In [75]:
import tensorflow as tf

In [79]:
tf.placeholder(dtype.float32,shape=(400,400))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [78]:
tf.compat.v1.disable_eager_execution()

In [80]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [81]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [82]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [83]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [84]:
import numpy as np

In [85]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [86]:
with tf.compat.v1.Session() as sess:
  d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

In [87]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)